# Generated by Django 4.0.1 on 2023-08-15 19:01

import advertisement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0002_alter_advertisementmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modelcomment',
            options={},
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementBody1',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementBody2',
            field=models.TextField(blank=True, max_length=1700, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementBody3',
            field=models.TextField(blank=True, max_length=1700, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementBody4',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementBody5',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementImage1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[500, 300], upload_to=advertisement.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementImage2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[500, 300], upload_to=advertisement.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementImage3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[500, 300], upload_to=advertisement.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementImage4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[500, 300], upload_to=advertisement.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementImage5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[500, 300], upload_to=advertisement.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementImageMain',
            field=models.ImageField(blank=True, null=True, upload_to=advertisement.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='AdvertisementTitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='Advertisement_Created_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='Advertisement_Updated_At',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='Advertisementquestion1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='Advertisementquestion2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='Advertisementquestion3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='Advertisementquestion4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='Advertisementquestion5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='Advertisementquote',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='Slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='vip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='commentposted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='motherpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertisementmodel'),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
