# Generated by Django 4.0.1 on 2023-08-15 09:44

import Blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'مجله', 'verbose_name_plural': 'مجله ها'},
        ),
        migrations.AlterModelOptions(
            name='modelcomment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظر ها'},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogBody1',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='توضیحات 1'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogBody2',
            field=models.TextField(blank=True, max_length=1700, null=True, verbose_name='توضیحات 2'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogBody3',
            field=models.TextField(blank=True, max_length=1700, null=True, verbose_name='توضیحات 3'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogBody4',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='توضیحات 4'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogBody5',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='توضیحات 5'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogImage1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[500, 300], upload_to=Blog.models.upload_image_path, verbose_name='عکس 1'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogImage2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[500, 300], upload_to=Blog.models.upload_image_path, verbose_name='عکس 2'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogImage3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[500, 300], upload_to=Blog.models.upload_image_path, verbose_name='عکس 3'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogImage4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[500, 300], upload_to=Blog.models.upload_image_path, verbose_name='عکس 4'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogImage5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[500, 300], upload_to=Blog.models.upload_image_path, verbose_name='عکس 5'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogImageMain',
            field=models.ImageField(blank=True, null=True, upload_to=Blog.models.upload_image_path, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='BlogTitle',
            field=models.CharField(max_length=200, verbose_name='نام مجله'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Blog_Created_At',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Blog_Updated_At',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ابدیت'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Blogquestion1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سوال 1'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Blogquestion2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سوال 2'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Blogquestion3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سوال 3'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Blogquestion4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سوال 4'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Blogquestion5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سوال 5'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Blogquote',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='متن کوتاه مهم از مجله'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='هشتگ'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='vip',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='صفحه خانه'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='تایید'),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='commentposted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='motherpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.blogmodel', verbose_name='پست مادر'),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام'),
        ),
    ]
