# Generated by Django 4.0.1 on 2023-08-15 19:13

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSliderPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن 1')),
                ('text2', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن 2')),
                ('text3', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن 3')),
                ('text4', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن 4')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Home.models.upload_image_path_slider_photo, verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'عکس اسلایدر صفحه خانه',
                'verbose_name_plural': 'عکس های اسلایدر صفحه خانه',
            },
        ),
        migrations.CreateModel(
            name='ModelContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما',
            },
        ),
    ]
