# Generated by Django 4.0.1 on 2023-08-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesliderphotomodel',
            name='text1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متن اسلایدرن 1'),
        ),
    ]
