# Generated by Django 4.0.1 on 2023-08-15 18:36

import Home.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_homesliderphotomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesliderphotomodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homesliderphotomodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='homesliderphotomodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='homesliderphotomodel',
            name='title',
        ),
        migrations.AddField(
            model_name='homesliderphotomodel',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[1920, 1920], upload_to=Home.models.upload_image_path_slider_photo, verbose_name='عکس'),
        ),
    ]
