# Generated by Django 4.0.1 on 2023-08-15 18:40

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_homesliderphotomodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesliderphotomodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Home.models.upload_image_path_slider_photo, verbose_name='عکس'),
        ),
    ]
