# Generated by Django 4.0.1 on 2023-08-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_homesliderphotomodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesliderphotomodel',
            options={'verbose_name': 'عکس های اسلایدر صفحه خانه'},
        ),
        migrations.AlterModelOptions(
            name='modelcontact',
            options={'verbose_name': 'ارتباط با ما'},
        ),
        migrations.AddField(
            model_name='homesliderphotomodel',
            name='text1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متن 1'),
        ),
        migrations.AddField(
            model_name='homesliderphotomodel',
            name='text2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متن 2'),
        ),
        migrations.AddField(
            model_name='homesliderphotomodel',
            name='text3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متن 3'),
        ),
        migrations.AddField(
            model_name='homesliderphotomodel',
            name='text4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متن 4'),
        ),
    ]
