# Generated by Django 4.0.1 on 2023-08-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_homesliderphotomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesliderphotomodel',
            options={'verbose_name': 'عکس اسلایدر صفحه خانه', 'verbose_name_plural': 'عکس های اسلایدر صفحه خانه'},
        ),
        migrations.AlterModelOptions(
            name='modelcontact',
            options={'verbose_name': 'ارتباط با ما', 'verbose_name_plural': 'ارتباط با ما'},
        ),
    ]
