# Generated by Django 4.0.1 on 2023-09-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_homesliderphotomodel_text1'),
        ('Home', '0006_alter_homesliderphotomodel_options_and_more'),
    ]

    operations = [
    ]
