# Generated by Django 4.0.1 on 2023-08-15 19:22

import Shop.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='نام دسته بندی')),
                ('url_name', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='نام انگلیسی دسته بندی')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['top', 'left', 'bottom', 'right'], force_format='JPEG', keep_meta=True, null=True, quality=99, size=[1920, 1920], upload_to=Shop.models.upload_image_path_category, verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام زیر دسته بندی')),
                ('url_name', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='نام زیر دسته بندی انگلیسی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.categories', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'زیر دسته بندی',
                'verbose_name_plural': 'زیر دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='subsubcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام زیر زیر دسته بندی')),
                ('url_name', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='نام زیر زیر دسته بندی انگلیسی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.subcategories', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'زیر زیر دسته بندی',
                'verbose_name_plural': 'زیر زیر دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=60, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='نام انگلیسی محصول')),
                ('ProductBody', models.TextField(blank=True, max_length=800, null=True, verbose_name='توضیحات 1')),
                ('ProductBody2', models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات دو')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[1080, 720], upload_to=Shop.models.upload_image_path_product, verbose_name='عکس 1')),
                ('image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[1080, 720], upload_to=Shop.models.upload_image_path_product, verbose_name='عکس 2')),
                ('image3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[1080, 720], upload_to=Shop.models.upload_image_path_product, verbose_name='عکس 3')),
                ('image4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[1080, 720], upload_to=Shop.models.upload_image_path_product, verbose_name='عکس 4')),
                ('image5', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[1080, 720], upload_to=Shop.models.upload_image_path_product, verbose_name='عکس 5')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد')),
                ('Dimensions', models.CharField(blank=True, max_length=60, null=True, verbose_name='چند در چند')),
                ('Weight', models.SmallIntegerField(blank=True, null=True, verbose_name='وزن')),
                ('WaterWeight', models.SmallIntegerField(blank=True, null=True, verbose_name='مخزن آب')),
                ('HowMany', models.CharField(blank=True, choices=[('یک نفره', 'یک نفره'), ('دو نفره و سه نفره', 'دو نفره و سه نفره'), ('چهار نفره', 'چهار نفره'), ('شش نفره', 'شش نفره'), ('هشت نفره', 'هشت نفره')], max_length=60, null=True, verbose_name='چند نفره')),
                ('Tags', django_mysql.models.ListCharField(models.CharField(max_length=50), blank=True, max_length=2000, null=True, size=30, verbose_name='هشتگ')),
                ('OptionsList', django_mysql.models.ListCharField(models.CharField(max_length=50), blank=True, max_length=2000, null=True, size=30, verbose_name='امکانات')),
                ('OptionsWithJaccuzi', django_mysql.models.ListCharField(models.CharField(max_length=50), blank=True, max_length=2000, null=True, size=30, verbose_name='امکانات جکوزی')),
                ('OptionsWithOne', django_mysql.models.ListCharField(models.CharField(max_length=50), blank=True, max_length=2000, null=True, size=30, verbose_name='امکانات وان')),
                ('price_type1', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت تیپ 1')),
                ('price_type2', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت تیپ 2')),
                ('price_type3', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت تیپ 3')),
                ('show_price', models.CharField(blank=True, default='0', max_length=30, verbose_name='')),
                ('show_price2', models.CharField(blank=True, default='0', max_length=30, verbose_name='')),
                ('show_price3', models.CharField(blank=True, default='0', max_length=30, verbose_name='')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='پاک شود؟')),
                ('firstpage', models.BooleanField(blank=True, default=False, null=True, verbose_name='صفحه خانه')),
                ('Seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_main', to='Shop.categories', verbose_name='دسته بندی')),
                ('sub_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.subcategories', verbose_name='زیر دسته بندی')),
                ('sub_sub_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.subsubcategories', verbose_name='زیر زیر دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ModelCommentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('content', models.TextField(max_length=1000, verbose_name='فروشنده')),
                ('commentposted', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('accepted', models.BooleanField(default=False, verbose_name='تایید؟')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.productmodel', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
